import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'
import type { RoleId, Currency } from '../types'
import { ROLES } from '../data/roles'

export interface FirmSettings {
  firmName: string
  currency: Currency
  customBank?: import('../types').WorkItemDefinition[]
  recentWorkItemIds: string[]
  defaultMarginPct: number
  defaultOverheadPct: number
  defaultSprintWeeks: number
  defaultWorkingDaysPerWeek: number
  defaultProjectMonths: number
  rateCard: Partial<Record<RoleId, number>>      // base GBP rates
  useBlendedRate: boolean                        // if true, apply blendedRate to all roles
  blendedRate: number                            // single GBP daily rate for all roles
  // Effort calibration multipliers (applied on top of wizard base values)
  effortScale: {
    simple: number; medium: number; complex: number
    infraMinimal: number; infraStandard: number; infraComplex: number
  }
  // FX conversion rates (base = GBP 1.0)
  fxRates: { USD: number; EUR: number; INR: number }
  // Default cost rate as % of billing rate (used when costRateCard not set per role)
  defaultCostRatePct: number
  // Contingency % applied when a risk band is selected
  contingencyByBand: { green: number; amber: number; red: number; black: number; unknown: number }
  // Labour/gross margin traffic-light thresholds
  marginThresholds: { green: number; amber: number }
  // OpEx monthly defaults generated by the scope configurator (GBP)
  opexDefaults: {
    cloudStandard: number; cloudComplex: number
    onPremStandard: number; onPremComplex: number
    monitoring: number
  }
  // Phase duration split for timeline (values = %, must sum to 100)
  phaseSplits: {
    discovery: number; design: number; build: number; qa: number
    uat: number; golive: number; hypercare: number
  }
  // Fallback daily rate when a role has no rate configured (GBP)
  fallbackDayRate: number
}

const DEFAULT_RATE_CARD = Object.fromEntries(
  (Object.keys(ROLES) as RoleId[]).map(r => [r, ROLES[r].defaultRate])
) as Record<RoleId, number>

export const DEFAULT_SETTINGS: FirmSettings = {
  firmName: '',
  currency: 'USD',
  recentWorkItemIds: [],
  defaultMarginPct: 25,
  defaultOverheadPct: 10,
  defaultSprintWeeks: 2,
  defaultWorkingDaysPerWeek: 5,
  defaultProjectMonths: 6,
  rateCard: DEFAULT_RATE_CARD,
  useBlendedRate: false,
  blendedRate: 600,
  effortScale: { simple: 0.7, medium: 1.0, complex: 1.5, infraMinimal: 0.4, infraStandard: 1.0, infraComplex: 1.8 },
  fxRates: { USD: 1.27, EUR: 1.17, INR: 105 },
  defaultCostRatePct: 55,
  contingencyByBand: { green: 10, amber: 20, red: 35, black: 50, unknown: 20 },
  marginThresholds: { green: 30, amber: 15 },
  opexDefaults: { cloudStandard: 3000, cloudComplex: 8000, onPremStandard: 2000, onPremComplex: 5000, monitoring: 500 },
  phaseSplits: { discovery: 10, design: 10, build: 45, qa: 15, uat: 10, golive: 5, hypercare: 5 },
  fallbackDayRate: 600,
}

export interface SettingsStore {
  settings: FirmSettings
  updateSettings: (patch: Partial<FirmSettings>) => void
  setRate: (role: RoleId, gbpRate: number) => void
  setEffortScale: (key: keyof FirmSettings['effortScale'], value: number) => void
  resetRates: () => void
  resetEffortScale: () => void
  addRecentWorkItem: (id: string) => void
}

export const useSettingsStore = create<SettingsStore>()(
  persist(
    (set) => ({
      settings: DEFAULT_SETTINGS,

      updateSettings: (patch) =>
        set(s => ({ settings: { ...s.settings, ...patch } })),

      setRate: (role, gbpRate) =>
        set(s => ({
          settings: {
            ...s.settings,
            rateCard: { ...s.settings.rateCard, [role]: gbpRate },
          },
        })),

      setEffortScale: (key, value) =>
        set(s => ({
          settings: {
            ...s.settings,
            effortScale: { ...s.settings.effortScale, [key]: value },
          },
        })),

      resetRates: () =>
        set(s => ({ settings: { ...s.settings, rateCard: DEFAULT_RATE_CARD } })),

      resetEffortScale: () =>
        set(s => ({
          settings: {
            ...s.settings,
            effortScale: DEFAULT_SETTINGS.effortScale,
          },
        })),

      addRecentWorkItem: (id) =>
        set(s => ({
          settings: {
            ...s.settings,
            recentWorkItemIds: [id, ...(s.settings.recentWorkItemIds ?? []).filter(x => x !== id)].slice(0, 8),
          },
        })),
    }),
    {
      name: 'cortex-settings-v1',
      storage: createJSONStorage(() => localStorage),
    }
  )
)
